spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_list
spring.datasource.username=shopping_list
spring.datasource.password=shopping_list

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
