-- Schema inicial. Aplicado automaticamente em Postgres novo via docker-compose.

CREATE TABLE IF NOT EXISTS plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_plans_name UNIQUE (name)
);

INSERT INTO plans (id, name)
OVERRIDING SYSTEM VALUE
VALUES (1, 'Free'),
       (2, 'Premium')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('plans', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM plans)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    preferred_currency VARCHAR(3) NOT NULL DEFAULT 'BRL',
    plan_id BIGINT NOT NULL REFERENCES plans (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_plan_id ON users (plan_id);

CREATE TABLE IF NOT EXISTS email_verification_code (
    email VARCHAR(255) PRIMARY KEY,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shopping_list_items (
    item_id VARCHAR(64) PRIMARY KEY,
    list_id VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    price DOUBLE PRECISION NULL,
    expiry VARCHAR(64) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shopping_list_items_list_id ON shopping_list_items (list_id);
